#OUTDIR: /path/to/output 
READS_DIR: bams # don't add the reads files, just the directory where they are
SAMPLE_LIST: samples.csv
REFERENCE: ./reference.fa
CONTIGS_IGNORE: ./ignore.txt
SPECIES: chicken
PREFIX: test
NUM_CHRS: 50
BWA_MEM_M: Y
